### ISSUE TITLE
Fix warnings introduced in elixir 1.15

### ISSUE THREAD

**Issue by thomasdziedzic-calmwave** [Strech/avrora#108]
When upgrading to elixir 1.15, I got a bunch of warnings: `warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead`

I think this is because elixir has now switched to the erlang logger in 1.15.

Some areas that display this issue: https://github.com/search?q=repo%3AStrech%2Favrora%20Logger.warn&type=code

**Comment by thomasdziedzic-calmwave** [comment]
Ah looks like someone already opened a PR to potentially fix this issue: https://github.com/Strech/avrora/pull/107

**Comment by Strech** [comment]
Thanks for reporting @thomasdziedzic-calmwave. The issue was fixed in [0.27](https://github.com/Strech/avrora/releases/tag/v0.27.0) release
