### ISSUE TITLE
Strange {:error, %ArgumentError{message: "argument error"}}

### ISSUE THREAD

**Issue by fxn** [Strech/avrora#21]
I am not sure this is an issue with Avrora, but have nailed down to something minimal in which only Phoenix channels and Avrora are involved.

The summary of the problem is that if a channel encodes, it errs if you exercise it in more than one test. Weird, uh?

To demonstrate it, I have created [this minimal Phoenix application](https://github.com/fxn/avrora_issue). The application has [one simple Avro schema](https://github.com/fxn/avrora_issue/blob/master/priv/schemas/com/example/User.avsc), and [a channel](https://github.com/fxn/avrora_issue/blob/master/lib/avrora_issue_web/channels/avrora_channel.ex) that just encodes a map when it receives a message.

Now, the surprising part is that the command

```
mix test test/avrora_issue_web/channels/avrora_channel_test.exs
```

runs [two tests](https://github.com/fxn/avrora_issue/blob/master/test/avrora_issue_web/channels/avrora_channel_test.exs) and fails with this output:

```
{:error, %ArgumentError{message: "argument error"}}
20:38:24.384 [error] GenServer #PID<0.282.0> terminating
** (MatchError) no match of right hand side value: {:error, %ArgumentError{message: "argument error"}}
    (avrora_issue) lib/avrora_issue_web/channels/avrora_channel.ex:9: AvroraIssueWeb.AvroraChannel.handle_in/3
    (phoenix) lib/phoenix/channel/server.ex:280: Phoenix.Channel.Server.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{event: "encode", join_ref: nil, payload: nil, ref: #Reference<0.2008719544.1328545796.244887>, topic: "avrora"}


  1) test second test (AvroraIssueWeb.AvroraChannelTest)
     test/avrora_issue_web/channels/avrora_channel_test.exs:16
     ** (EXIT from #PID<0.281.0>) an exception was raised:
         ** (MatchError) no match of right hand side value: {:error, %ArgumentError{message: "argument error"}}
             (avrora_issue) lib/avrora_issue_web/channels/avrora_channel.ex:9: AvroraIssueWeb.AvroraChannel.handle_in/3
             (phoenix) lib/phoenix/channel/server.ex:280: Phoenix.Channel.Server.handle_info/2
             (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
             (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
             (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

But, if you run each test by itself, they pass:

```
% mix test test/avrora_issue_web/channels/avrora_channel_test.exs:16
Excluding tags: [:test]
Including tags: [line: "16"]

{:ok,
 <<79, 98, 106, 1, 3, 134, 2, 20, 97, 118, 114, 111, 46, 99, 111, 100, 101, 99,
   8, 110, 117, 108, 108, 22, 97, 118, 114, 111, 46, 115, 99, 104, 101, 109, 97,
   202, 1, 123, 34, 110, 97, 109, 101, 115, 112, 97, 99, 101, ...>>}
.
```

I can't for the life of me explain why this might happen, do you have any idea?

**Comment by tarcisiozf** [comment]
I've had the same problem, had to use a internal fork from a previous version.

**Comment by Strech** [comment]
@fxn Hey, thanks for this usecase example. I will take a look 🔎

**Comment by fxn** [comment]
I have simplified the reproduction steps. Channels are not necessary, it happens with controllers too.

The [repository with the example app](https://github.com/fxn/avrora_issue) has been updated. WebSockets are removed, and there is a vanilla `PageController` that just encodes. The test suite of that contoller shows the problem. It has two tests that make requests to the same action. They pass individually, but do not pass together.

```
% mix test test/avrora_issue_web/controllers/page_controller_test.exs  
{:ok,
 <<79, 98, 106, 1, 3, 134, 2, 20, 97, 118, 114, 111, 46, 99, 111, 100, 101, 99,
   8, 110, 117, 108, 108, 22, 97, 118, 114, 111, 46, 115, 99, 104, 101, 109, 97,
   202, 1, 123, 34, 110, 97, 109, 101, 115, 112, 97, 99, 101, ...>>}
.{:error, %ArgumentError{message: "argument error"}}


  1) test 1 (AvroraIssueWeb.PageControllerTest)
     test/avrora_issue_web/controllers/page_controller_test.exs:4
     ** (MatchError) no match of right hand side value: {:error, %ArgumentError{message: "argument error"}}
     code: get(conn, "/")
     stacktrace:
       ...
```

**Comment by Strech** [comment]
@fxn Good news, thanks to provided test case, I've manage to find out where is the problem and I'm working on a fix. The bad news are – it's not related to tests it's a general issues.

**TLRD;**

I didn't understand how long and when ETS will be removed, now I know.

**Complete answer:**

It turn out that ETS belongs to the process where it was created, so in the example you create first test case encodes the schema, schema get parsed and ETS table created and bound to the ... (ta-ba-dums) .... process of a Phoenix controller ... which will die and another test case will run, BUT `Avrora.Storage.Memory` are sharing state between those 2 test cases and have a reference to already non-existing ETS table because it was cleaned when Phoenix process exists.

Hence this behaviour easily appear on a normal conroller flow, just request the same resource twice.

The fix will include 2 things:

1. All the schema ETS tables will be re-owned by a `Avrora.Storage.Memory` as the main demanding module
2. A test helper to remove state sharing will be added

**Comment by fxn** [comment]
Thanks!

**Comment by Strech** [comment]
@fxn @tarcisiozf Hey guys, I've finished the new version and here is a branch https://github.com/Strech/avrora/pull/22

It will fix an issue with or without test modifications and the difference is only do you want to share state or not (of course not). Here is an example of what will happen in case of the ETS tables gone:

```txt
iex(1)> Avrora.encode(%{"login" => "fxn"}, schema_name: "com.example.User")
[debug] reading schema `com.example.User` from the file /Volumes/SSDCard/Development/github/avrora_issue/priv/schemas/com/example/User.avsc
{:ok,
 <<79, 98, 106, 1, 3, 134, 2, 20, 97, 118, 114, 111, 46, 99, 111, 100, 101, 99,
   8, 110, 117, 108, 108, 22, 97, 118, 114, 111, 46, 115, 99, 104, 101, 109, 97,
   202, 1, 123, 34, 110, 97, 109, 101, 115, 112, 97, 99, 101, ...>>}

iex(2)> Avrora.encode(%{"login" => "fxn"}, schema_name: "com.example.User")
{:ok,
 <<79, 98, 106, 1, 3, 134, 2, 20, 97, 118, 114, 111, 46, 99, 111, 100, 101, 99,
   8, 110, 117, 108, 108, 22, 97, 118, 114, 111, 46, 115, 99, 104, 101, 109, 97,
   202, 1, 123, 34, 110, 97, 109, 101, 115, 112, 97, 99, 101, ...>>}

iex(3)> Process.exit(Process.whereis(Avrora.ETS), [])
true

iex(4)> Avrora.encode(%{"login" => "fxn"}, schema_name: "com.example.User")
[debug] reading schema `com.example.User` from the file /Volumes/SSDCard/Development/github/avrora_issue/priv/schemas/com/example/User.avsc
{:ok,
 <<79, 98, 106, 1, 3, 134, 2, 20, 97, 118, 114, 111, 46, 99, 111, 100, 101, 99,
   8, 110, 117, 108, 108, 22, 97, 118, 114, 111, 46, 115, 99, 104, 101, 109, 97,
   202, 1, 123, 34, 110, 97, 109, 101, 115, 112, 97, 99, 101, ...>>}
```

Any feedback is appreciated 🤝

**Comment by fxn** [comment]
Thanks for working on this :), my test suite passes with this branch.

I am not familiar with the implementation, but let me ask you a question: Is the memory storage and internal type of storage that acts as a cache to avoid hitting the registry or file system? Why isn't that GenServer enough to address this?

**Comment by Strech** [comment]
@fxn Technically yes, `Avrora.Storage.Memory` is just an in-memory cache. But it follows the same behavior as all other `Avrora.Storage`s. And if we want to stick to 1 owner for all `:ets` tables, then `Avrora.Schema` as the module who generates those tables should transfer ownership.

And here I have an OOP dilemma.

`Avrora.Schema` is a stupid module that just knows how to parse JSON and generate the structure of himself. And it should not know that some ownership exists or that it should be granted (also some `Process.whereis(...)` will appear, which mean I don't control my own modules).

At the same time if I want to add ownership to `Avrora.Storage.Memory` it should accept a grant and handle that message, which looks odd from the responsibilities perspective of Storage behavior.

Hence I decided to add the ETS host process which you can ask to create a new table and at the same time, it will be automatically a parent for them.

@fxn you think it's overcomplicated?

**Comment by fxn** [comment]
@Strech I don't know! :) I'll read the source code more in detail to understand it better.

**Comment by Strech** [comment]
@fxn Cool will be great to have another pair of eyes. I will release a new version then, and if you will have any suggestions, I can apply them in a next iteration 👍

**Comment by fxn** [comment]
@Strech perfect, thanks for the fix!

**Comment by Strech** [comment]
@fxn @tarcisiozf Guys, [release 0.9.0](https://github.com/Strech/avrora/releases/tag/v0.9.0) is out! Thanks for your participation 👏
