### ISSUE TITLE
Decoding an encoded record wraps the produced map in a list

### ISSUE THREAD

**Issue by kevinbader** [Strech/avrora#28]
Hi,

thanks for the library, looks really promising! However, I stumbled over the following, which _seems_ like a bug to me.

Consider the following Avro schema:

```json
{
  "namespace": "foo",
  "type": "record",
  "name": "Bar",
  "version": "1.0",
  "fields": [
    {
      "name": "baz",
      "type": "string"
    }
  ]
}
```

This schema can be used to encode `%{"baz" => "test"}`:

```elixir
iex> {:ok, encoded} = Avrora.encode(%{"baz" => "test"}, schema_name: "foo.Bar")
{:ok,
 <<79, 98, 106, 1, 3, 144, 2, 20, 97, 118, 114, 111, 46, 99, 111, 100, 101, 99,
   8, 110, 117, 108, 108, 22, 97, 118, 114, 111, 46, 115, 99, 104, 101, 109, 97,
   212, 1, 123, 34, 110, 97, 109, 101, 115, 112, 97, 99, 101, ...>>}
```

However, when decoding this again, the result is not a map like I would've expected; instead, the map is wrapped in a list:

```elixir
iex> Avrora.decode(encoded)
{:ok, [%{"baz" => "test"}]}
```

Sure enough, encoding this again fails:

```elixir
iex> Avrora.encode([%{"baz" => "test"}], schema_name: "foo.Bar")
** (FunctionClauseError) no function clause matching in Avrora.Encoder.encode/2
```

**Comment by Strech** [comment]
Hi @kevinbader, this is not a bug. When you don't have a schema registry, by default Avrora is using Avro [Object Container FIles](https://avro.apache.org/docs/1.8.1/spec.html#Object+Container+Files) format, which assumes that you have always a list.

You can fine that under `format` section in the [README](https://github.com/Strech/avrora#encode2).

Here is how you can make it plain:

```
iex(3)> Avrora.encode(%{"baz" => "test"}, schema_name: "foo.Bar")  
09:18:14.875 [debug] reading schema `foo.Bar` from the file ./tmp/schemas/foo/Bar.avsc
{:ok,
 <<79, 98, 106, 1, 3, 144, 2, 20, 97, 118, 114, 111, 46, 99, 111, 100, 101, 99,
   8, 110, 117, 108, 108, 22, 97, 118, 114, 111, 46, 115, 99, 104, 101, 109, 97,
   212, 1, 123, 34, 110, 97, 109, 101, 115, 112, 97, 99, 101, ...>>}
iex(4)> Avrora.encode(%{"baz" => "test"}, schema_name: "foo.Bar", format: :plain)
{:ok, "\btest"}
iex(5)> Avrora.decode("\btest", schema_name: "foo.Bar")
{:ok, %{"baz" => "test"}}
```

🤔 not sure why in `:plain` format you see it as a string and not as a charlist, maybe it's an `iex` thing but just in case will check

**Comment by kevinbader** [comment]
Hi @Strech,

thanks for your quick response! From the docs I couldn't really tell that using OCF would always result in a list, even in case there is only a single map in the container. Given what you wrote, however, I propose to change [the spec of encode](https://github.com/Strech/avrora/blob/master/lib/avrora/encoder.ex#L111) to reflect this; currently Dialyzer thinks it always returns a binary and never a list:

```elixir
@spec encode(map(), keyword(String.t())) :: {:ok, binary()} | {:error, term()}
```

Thanks!

**Comment by Strech** [comment]
Evening @kevinbader,

> From the docs I couldn't really tell that using OCF would always result in a list

I re-read the docs and what I can quote from the docs:

1. 
> Avro includes a simple object container file format. A file has a schema, and all objects stored in the file must be written according to that schema, using binary encoding. Objects are stored in blocks that may be compressed

2. 
> A file data block consists of:
>   - A long indicating the count of objects in this block.
>   - A long indicating the size in bytes of the serialized objects in the current block, after any codec is applied
>   - The serialized objects. If a codec is specified, this is compressed by that codec.

As you can see, it always plural, as I understand it a block of objects can include just one for sure, but it's considered to be a container of objects and in Elixir/Erlang world it's a `List`

> I propose to change the spec of encode to reflect this; currently Dialyzer thinks it always returns a binary and never a list:

Completely agree 👍 Will do it

**Comment by kevinbader** [comment]
You're completely right - thanks!

**Comment by Strech** [comment]
Hey @kevinbader sorry for a long response, but I've updated master with updated typespec for `Avrora.Encoder.decode/1` and `Avrora.Encoder.decode/2`
