### ISSUE TITLE
Subject not found

### ISSUE THREAD

**Issue by fxn** [Strech/avrora#40]
Hi! I am a bit lost here, let me share with you this issue in case it happened to you too.

The library is trying to register a brand new schema, but it fails to do so. The result of `http_client().post(payload, headers)` in `http_client_post/2` is

```
{:error, %{"error_code" => 40401, "message" => "Subject not found"}}
```

but I cannot understand how's that possible, since the [API of the registry](https://docs.confluent.io/current/schema-registry/develop/api.html) does not have 40401 among its error codes for that `POST` request.

Have you ever seen this? Perhaps there's a previous step in which you need to create the subject?

**Comment by fxn** [comment]
Solved.

The registry in this platform is not Confluent's. Turns out new subjects need an explicit creation step in this one.

**Comment by Strech** [comment]
@fxn Glad that issue resolved. Do anything that this library can improve emerge? I'm not quite sure that I understand about an explicit step. Technically the subject is registered every time you encode the payload

**Comment by fxn** [comment]
I don't have enough perspective to suggest an improvement.

The first time you encode, the library performs a `POST` to register the schema, and subsequent encodings use the returned ID. Using Confluent's registry, if the subject does not exist, it is created when you `POST`. This has worked flawlessly in development using the Docker image `confluentinc/cp-schema-registry`.

However, when I started deploying this project to company servers, that initial `POST` was failing with

```
{:error, %{"error_code" => 40401, "message" => "Subject not found"}}
```

Turns out, this platform is actually using https://github.com/hortonworks/registry, and this registry does not auto create subjects. If the subject is new, you need to manually create the subject first with a `POST` to

```
/api/v1/schemaregistry/schemas
```

that has a series of special attributes like `schemaGroup`.

Once the new subject is created, then avrora `POST`s to register a version work just fine as usual.

**Comment by Strech** [comment]
@fxn Thanks for the insights, I've checked the registry you are using, what I can say – they have 2 different endpoints for new and existing schema manipulations: [create schema](https://github.com/hortonworks/registry/blob/master/schema-registry/rest-service/src/main/java/com/hortonworks/registries/schemaregistry/webservice/SchemaRegistryResource.java#L389-L390) and [update schema](https://github.com/hortonworks/registry/blob/master/schema-registry/rest-service/src/main/java/com/hortonworks/registries/schemaregistry/webservice/SchemaRegistryResource.java#L440-L441).

This is an additional and a bit different behavior that I need to explore in the future. I have a plan to support out-of-band behavior and currently already have a few issues and ideas to implement, like:

* Schema registration task
* Read-only behavior for registry storage (out-of-band)

And seems it will be cool to implement support for a new registry (I guess)
