### ISSUE TITLE
Incorrect typespec for `Avrora.Encoder.encode/2`

### ISSUE THREAD

**Issue by soundmonster** [Strech/avrora#55]
The typespec states that the second argument of `encode/2` is a keyword list with string values:
```elixir
@spec encode(map(), keyword(String.t())) :: {:ok, binary()} | {:error, term()}
```

The two allowed keys in the keyword are `schema_name` (string) and `format` (_atom_). Calling this function with the format explicitly set to e.g. `:registry` causes Dialyzer to complain.

https://github.com/Strech/avrora/blob/c12c3147ebd6f0a6c0253cc4b2450a84100446bb/lib/avrora/encoder.ex#L103

This is a low priority issue that is easily handled with an ignore list for Dialyzer. I'll see if I find time to file a PR to fix this (maybe also going over other type specs to see if there's any inconsistencies).

**Comment by Strech** [comment]
Hey @soundmonster thanks for your effort, I very appreciate it. I've closed your PR and the issue with [v0.14.1 release]( https://github.com/Strech/avrora/releases/tag/v0.14.1). Thanks a lot for the help!
