### ISSUE TITLE
Support for multiple registries

### ISSUE THREAD

**Issue by arusahni** [Strech/avrora#61]
First off, thank you for the library! It's very convenient.

I'm currently encountering a challenge: I'm using a library that, too, uses Avrora. However, I'd like to use a different registry than  what the library is using. 

For example, the library is loading schemas from `./deps/library-name/priv/schemas`, and I'd like to use my own schemas located in `./priv/schemas`.

Is this something you would consider supporting?

**Comment by Strech** [comment]
Hey, @arusahni thanks for the issue 👋🏼 

I would like to get a bit more details. Is that library available to check out? Do you have an example that I can test (or a simple setup)? 

I think the functionality you are looking for should be possible with minimum effort, but I need a bit of time to try things out. Technically you can supervise your Avrora separate with its own settings ... in theory

**Comment by arusahni** [comment]
Unfortunately, the library isn't public.

I tried spinning up a separately-managed Avrora process for my application, but hit a roadblock with process name collisions. While I could rename the main process, I couldn't specify names for the `AvroSchemaStore` and `Memory` children.

To provide some context/structure:

```elixir
# library: ./lib/libname/Application.ex

defmodule LibName.Application do
  @moduledoc false

  use Application

  @impl Application
  def start(_type, _args) do
    schemas_path = Path.join([to_string(:code.priv_dir(:libname)), "schemas"])
    Application.put_env(:avrora, :schemas_path, schemas_path)

    children = [
      Avrora,
    ]

    opts = [strategy: :one_for_one, name: LibName.Supervisor]
    Supervisor.start_link(children, opts)
  end
end
```

From my application, it'd be nice to be able to spin up a managed Avrora process namespaced to the app, and with config distinct from the library's.

For now, I'm hacking around this by walking my local schemas directory, parsing the schemas, and then injecting them into the memory store with an infinite TTL 😬

**Comment by Strech** [comment]
Ah, I see. I think it would be cool to isolate Avrora while supervising it. I will check how it can be done correctly and keep syntax/usage simple as it now.

**Comment by arusahni** [comment]
@Strech That would be really neat! While I'm not an Elixir expert, I'm willing to assist with any dev work if there are low-hanging tasks you'd like to offload.

Also, I realize that I may not have been as precise with my earlier description of the config. Ideally, the library could continue to use its schemas, and my application could use its own schemas.

**Comment by Strech** [comment]
@arusahni Thanks for your offer, I will try to understand what we can do to implement that and will post a proposal that we can discuss and maybe check how we can split it 🤝

**Comment by Strech** [comment]
@arusahni Hey, a small heads ups about the progress. I've made a research and turns out that this feature will require significant changes in some internals. But at the same time, it will be quite an interesting challenge.

So now I'm working on it but I assume it will be hard to keep it as non-breaking changes.

**Comment by arusahni** [comment]
@Strech thank you for the update! I appreciate that you think this is worth including in Avrora despite the intrusiveness of the change. My offer to help still stands, so please do let me know if there's anything you could use a second set of hands on :keyboard:

**Comment by Strech** [comment]
Thanks for the offer @arusahni I appreciate it. I think once the concept of the changes will settle a bit I will post it as issues with description and you can pick any you like 🤝

**Comment by Strech** [comment]
@arusahni it turns out that I can introduce that feature without doing any breaking change. The configuration interface of the client module will be slightly different, but it will be compile-time, so who cares.

For more insights please check here #67

**Comment by Strech** [comment]
Hey @arusahni, thanks for your support and for raising this feature request. Starting [release 0.17](https://github.com/Strech/avrora/releases/tag/v0.17.0) Avrora supports multi-client configuration 🎉

**Comment by arusahni** [comment]
@Strech that's awesome! Thanks for all of this. I look forward to checking it out! I'll let you know how things shake out.

**Comment by Strech** [comment]
Waiting for any feedback 🤝
