### ISSUE TITLE
Getting a KeyError

### ISSUE THREAD

**Issue by thiamsantos** [Strech/avrora#7]
I'm getting exceptions when trying to parse a message that is not encoded with avro.
```
[error] GenServer #PID<0.584.0> terminating
** (KeyError) key :original not found in: %MatchError{term: "\"uuid\":\"f6ad9736-11f1-4887-845b-aa4d778a1b79\",\"deleted_at\":1565371184722}"}
    (avrora) lib/avrora/encoder.ex:86: Avrora.Encoder.do_decode/2
    (portal) lib/portal/consumers/pipe_deleted.ex:10: anonymous fn/1 in Portal.Consumers.PipeDeleted.handle_messages/1
    (elixir) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:783: Enum.each/2
    (portal) lib/portal/consumers/pipe_deleted.ex:9: Portal.Consumers.PipeDeleted.handle_messages/1
    (portal) lib/portal/consumers/pipe_deleted.ex:2: Portal.Consumers.PipeDeleted.handle_messages/2
    (elsa) lib/elsa/group/worker.ex:93: Elsa.Group.Worker.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {#PID<0.466.0>, {:kafka_message_set, "pipe_deleted", 0, 12, [{:kafka_message, 11, "", "{\"uuid\":\"f6ad9736-11f1-4887-845b-aa4d778a1b79\",\"deleted_at\":1565371184722}", :create, 1565371726633, []}]}}
State: %Elsa.Group.Worker.State{config: [], generation_id: 36, handler: Portal.Consumers.PipeDeleted, handler_init_args: %{}, handler_state: %{}, name: :pipe_deleted, offset: 11, partition: 0, subscriber_pid: #PID<0.466.0>, topic: "pipe_deleted"}
```

I solved temporarily by using `Exception.message/1` https://github.com/thiamsantos/avrora/commit/2cfd0bf8a21ed83ab1cb0bd968ee830c5c59461d.

But we may need to treat the root cause of this problem.

**Comment by Strech** [comment]
@thiamsantos can I ask you to give me a gist or something I can reproduce your issue?

**Comment by Strech** [comment]
@thiamsantos Hey, I get what you mean. I take a message from your backtrace and was able to reproduce an issue.

I fix error handling and now you should receive a correct error, like `{:error, %MatchError{...}}`

**Comment by cristopher-rodrigues** [comment]
> @thiamsantos Hey, I get what you mean. I take a message from your backtrace and was able to reproduce an issue.
> 
> I fix error handling and now you should receive a correct error, like `{:error, %MatchError{...}}` in [v0.3.1](https://github.com/Strech/avrora/releases/tag/v0.3.1), thanks for your contribusion!

Great thanks to having it solve so fast.
