### ISSUE TITLE
Maintain a CHANGELOG?

### ISSUE THREAD

**Issue by fxn** [Strech/avrora#74]
A CHANGELOG with a summary of what matters to users in each release would be really useful when upgrading.

**Comment by Strech** [comment]
Hey, 👋🏼  I'm writing the release description as a changelog-like. Not sure is there any good automated way to do so?

**Comment by fxn** [comment]
Where's that release description?

**Comment by Strech** [comment]
It's on the [Releases](https://github.com/Strech/avrora/releases) page

**Comment by fxn** [comment]
Ohhh, totally missed that. That was what I was looking for. Thanks!

**Comment by Strech** [comment]
You are welcome 🤝
