### ISSUE TITLE
Dialyzer issues with private clients

### ISSUE THREAD

**Issue by LostKobrakai** [Strech/avrora#77]
When creating a private client dialyzer does return a bunch of errors like mismatch between `Avrora.Schema` and `CustomClient.Schema`, but also a bunch more I'm not exactly sure what they're related to.

**Comment by Strech** [comment]
Hi @LostKobrakai, can you please provide a sample of the output and maybe steps to reproduce it. It might be that private clients need a few rounds of improvements.

**Comment by LostKobrakai** [comment]
It seems like most surfaced just by copy pasting one of the test modules for private clients into `lib/`, so dialyzer does check them.
