### ISSUE TITLE
Get schema name on decode

### ISSUE THREAD

**Issue by ricn** [Strech/avrora#82]
Hello,

Is it possible to get the schema name that was used when decoding? I can't find it in the documentation.

I'm thinking of something like this: {:ok, decoded, schema_name} = Avrora.decode(message)

**Comment by Strech** [comment]
Hi @ricn, I think currently when decoding schema registry encoded messages you will not be able to see the schema except maybe in the logs.

But you can use `Avrora.extract_schema/1` to retrieve schema the same way you decode the message. Does it make sense to you?

**Comment by ricn** [comment]
Hi @Strech, Aha thanks. That's exactly what I want :+1:

**Comment by Strech** [comment]
You are welcome @ricn 🤝
